name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build, Tag, and Push Docker Image
      run: |
        # Set the image name to include your Docker Hub username
        IMAGE_NAME=bids4u/auth  # Replace 'bids4u' with your Docker Hub username and 'auth' with the repo name
        
        # Get the short Git commit SHA and timestamp
        GIT_SHA=$(git rev-parse --short HEAD)
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        UNIQUE_TAG=${GIT_SHA}-${TIMESTAMP}

        # Build the Docker image with the unique tag
        docker build auth-back --file auth-back/Dockerfile --tag $IMAGE_NAME:$UNIQUE_TAG

        # Tag the latest version
        docker tag $IMAGE_NAME:$UNIQUE_TAG $IMAGE_NAME:latest

        # Debug: List images to verify tags
        docker images

        # Push both the unique tag and the latest tag
        docker push $IMAGE_NAME:$UNIQUE_TAG
